### ISSUE TITLE
Anchorが不安定問題

### ISSUE THREAD

**Issue by yt-ymmt** [yu-kgr/oimo.fm#11]
Anchor のアプリが毎回不安定なので録音方法を変更してもいいのかも？
yatteikiとかはPCで編集してるみたいだけど、繋ぎのジングル的なものは用意する必要がある。

**Comment by yu-kgr** [comment]
別の方のPodcastにお呼ばれしたので初期セットアップをしてたんですが、
PCかつQuickTimeで各自収録。保存した音源を編集している感じでした。
いくつかSE（音源）用意すればいけそうな気がするので、次あたりに一度検討しても良いかも

参考
https://paper.dropbox.com/doc/tsudokanai-radio-BwmQSeRif9vXshkngKCgT

**Comment by yt-ymmt** [comment]
こんなんもありました
https://medium.com/@r7kamura/yatteiki-fm-podcast-%E7%92%B0%E5%A2%83-2017-c3dbaaeea7d3

**Comment by yu-kgr** [comment]
▼ 参考
https://medium.com/soussune/テック系ポッドキャストの音声編集ソフトについて-ポストプロダクション編-72ad927db705

上記を参考にして、zencastr登録してみました。
各々の人ごとに音源が分割、DLできる所が決め手です。

▼ 収録時のinviteリンク
https://zencastr.com/yu_kgr/oimofm

▼収録音源が自動保存されるdropbox共有リンク 
https://www.dropbox.com/sh/rzov7s8lbk3sw8e/AACQNks4L2CA6YksZCBD6D7Va?dl=0
