### ISSUE TITLE
OIMO.fm #2 / Discussion

### ISSUE THREAD

**Issue by yt-ymmt** [yu-kgr/oimo.fm#12]
[OIMO.fm #0 / Discussion](https://github.com/yu-kgr/oimo.fm/issues/4)
[OIMO.fm #1 / Discussion](https://github.com/yu-kgr/oimo.fm/issues/5)

**Comment by yt-ymmt** [comment]
### Topic
- 1on1やってる？
    - Minakawa
        - 弊社でもお上の声が出て、色々な所で行い始めた傾向があるが…
            - 何を実現するためにやっていて、誰のためのものなのかがふわっとしてる感を感じた。
            - まだまだとりあえずやっているという印象がある。
            - 自分がやってたときは、行う目的を明確化、事前にアンケートを送信して、当日に答える内容を熟考してもらって話す。頻度は隔週に1回程度。我々が目指す目標に対して、個々でどういう課題があるのか？というものを軸とした話をしていた。
    - Yamamoto
        - 開始直後はラポール形成を意識して雑談ベースから入るのもいいかも
        - 普段からコミュニケーションがそこそこ取れているのなら、形式張ってもわりとついてこれそう
        - 謙虚・敬意・信頼が必要
        - 課題を指摘したり、答えを教える存在ではなく、メンティが階段を上る手助けをするべき（ってエンジニアリング組織論への招待に書いてありました）

- フレックス / リモートワークという働き方
    - Yamamoto
        - リモートワークはただのツールという概念として捉えている
        - オフラインで一瞬で終わるコミュニケーションも存在するため、ただ楽になるだけではない
        - 情報の非対称性をできるだけ作らないように `ジョハリの窓` を意識し続けることが必要
            - https://potect-a.com/wp-content/uploads/2018/10/johari-no-mado5.jpg
- 嫁との情報共有
    - Yamamoto
        - trello を導入したけれどリテラシーの差が発生し、冷蔵庫に貼ったホワイトボードに書くというアナログなソリューションに落ち着いた...
        - 旅行などの計画は notion で自分が作成して共有している

### Other
- 転職を考える（た）とき
- フリーライドする働き方の懸念
- マネージメントとは
    - ハイアウトプットマネージメント？

**Comment by yu-kgr** [comment]
IMO : 個人目標って立ててます？

**Comment by yt-ymmt** [comment]
明確には立ててません...！
職能や業界の will / can / must くらいはキャッチアップして適宜むきなおりすることはやってますかね。
フロントなら TypeScript は前提になってくるだろうし、SPAから揺り戻しで WebComponents がメインになる未来もあるかもなあとか。

**Comment by yu-kgr** [comment]
IMO : 自分、及び他人の持つ先入観線との付き合い方

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yu-kgr** [comment]
このチケットに記載されていた内容はすべて別途Issueとして記載したので、クローズします！
