### ISSUE TITLE
フレックス / リモートワークという働き方について

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#18]
バイソンさんの所はリモートワークを実施していると思うのですが、
自分はリモートワーク体験したことがないので実際どんな感じですか？という話を聞きたいやつ。

---

@yt-ymmt 
- リモートワークはただのツールという概念として捉えている
- オフラインで一瞬で終わるコミュニケーションも存在するため、ただ楽になるだけではない
- 情報の非対称性をできるだけ作らないように ジョハリの窓 を意識し続けることが必要
- https://potect-a.com/wp-content/uploads/2018/10/johari-no-mado5.jpg

@yu-kgr 
- 最近、これを見た（https://speakerdeck.com/daiksy/developer-summit-2018）
- 手段のひとつではあるけど、リモートワークを手段として選択する場合はお互いが気をつけなければならない紳士協定みたいなものがあるなぁという印象。
- 割と積極的にコミュニケーション取りたいタイプなので、個人的には厳しいんじゃないかなぁと思ってる（しらんけど）
- ちなみにマネージャーのリモートワークって無理なんじゃね？って思ってるんですがどうなんですかね。

**Comment by yt-ymmt** [comment]
ちょっと考えを整理します。

### リモートワークで考えないといけないこと
- 時間管理
  - 知的労働に対して時間で管理しようとすると難しい
- 情報の非対称性
  - 上に挙げてもらった ジョハリの窓 みたいなのは組織単位で根付いていないとリモートやその場にいない人が蚊帳の外に感じられてしまう
    - よってこれはリモート以前に組織の情報共有の風土の話であり、リモートワークによって顕在化したに過ぎない
  - サイボウズなどは雑談レベルでもslackのチャンネルに実況が立つ模様
    - 自分が参加していない場所でもログとして追える
- リモートワークの割合
  - 例えば、100人中90人がリモートの場合と、100人中10人がリモートだった場合では情報の非対称性などは後者のほうが起こる。
  - リモートワークを前提としたコミュニケーションが醸成されるには一定のリテラシーが必要
- フルリモートとリモート可の違い
  - リモート可は出社もできるけど、リモートを選択することができる
    - 移動時間を作業に充てられる。台風のときでもネットがあれば仕事ができる
  - フルリモートは基本出社できない。出張などすれば出社はできる
    - 地方などの優秀層を採用することができる
- 言語化能力
  - ドキュメントやslack上でのコミュニケーションにおいて、物事を言語化する能力が必要で、どうしても属人的な能力に依存する形になる
  - ついていけないとドキュメントやプロジェクトがうまくいかない -> オフラインで直接会って作業 -> リモートでもできている人いるのに...
    - リモートを目的としてしまうと、自己肯定感や自己効力感の低下につながる
- デジタル心理的安全性
  - slackなどのツールは上に書いたように言語能力が比較的高い人間やリテラシーに左右される
  - slack などのパブリックチャンネルで会話する人が固定になっていませんか？
    - 管理者はパブリックチャンネルの発言数やDM率を見たほうがよさそう
- マネージメント
  - オンラインでの会議やタスク管理ツールを介して、定量的な業務マネージメントはできる
  - 定性的な人事マネージメントはかなり苦労しそう（する）
    - フルリモートでも最初の1ヶ月はなんとかしてきてもらう、合宿などで定期的に会う場を設ける、定期的に雑談するオンライン会議を設定する、など工夫が必要
