### ISSUE TITLE
転職を考える（た）ときについて

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#20]
転職を考えるタイミングってなんなんですかね？

基本的には満足している場合は転職しないと思うので、
 自分にとってその環境では得ることができないものがある時になるかと思うんですが。

各々が転職時に考えたことについて、言える範囲で語りましょう。

↓ にかく

**Comment by yt-ymmt** [comment]
### 転職のモデル
#### 物理的に働けなくなった場合
- 病気
- 家庭の問題（介護、遠方に引っ越し etc）
- 天災
- etc

こういった類はそれで完結してしまうため議論する余地がない。

#### 水準に合わない場合
多分話したいのはこちら。
基本的に行動の背景には欲求が存在し、あらゆる欲求には個人の水準があり、これは状況によっても当然変わる。

- 給料（生活水準
- 人間関係
- 技術
- 会社の成長度
- 承認欲求
- 自己実現欲求

**Comment by yt-ymmt** [comment]
どういう時に仕事を辞めたくなるか - Konifar's ZATSU
http://konifar-zatsu.hatenadiary.jp/entry/2019/09/12/210130
