### ISSUE TITLE
会社として個人として「個人目標」を定義しているか？ 

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#23]
個人目標って決めているか？
- それは会社として定義しているのか？または個人的にも定義しているのか
- なんのために定義しているのか
- 実際定義してみてどうか？

**Comment by yt-ymmt** [comment]
- 自分の目標を立てることが難しい
  - 達成できていると感じたことが一回もない
  - そのときは少し背伸びしたレベルの目標にするが、業務と関係ない目標設定をする
    - 興味が煩雑になって達成できない

**Comment by yu-kgr** [comment]
「目標を設定しないと成長につながらない」みたいな前提条件にとらわれているのではないか

**Comment by yt-ymmt** [comment]
- どう個人目標を定義すればいいのか
  - ちょっと背伸びした目標設定
    - この指標がかなり難しい
- 目標設定
  - 本人の成長の礎になるもの
  - 本人の成長 => 組織の成長 が前提
  - マネージャーがハンドリングしてあげてほしいところ
    - 2つは業務ベース、1つは努力ベースにyamamotoはしてる

**Comment by yt-ymmt** [comment]
- 市場において自分がどこに位置しているか
- その上で自分がどうなりたいか
- 目標設定はそのなりたい自分へのマイルストーンとして設定すると良さそう
- 市場や取り巻く環境を知るために本を読んだり、LT会やカンファレンスに参加することは有効
- いろいろなエンジニアと話したり、ロールモデルになるような人物を見つけることで、自ずと目標というのは表現できるようになるのでは

**Comment by yu-kgr** [comment]
あらゆるスコープにおいて、どのようなふるまい・立ち位置でいたいのか（市場 / 会社）を考えて認識する
