### ISSUE TITLE
マネージャーの任命・オンボーディング

### ISSUE THREAD

**Issue by yt-ymmt** [yu-kgr/oimo.fm#25]
マネージャーという仕事は体力的にも精神的にも負荷が高い。アサインする人間もそうだし、管理される組織にも影響が出るため、アサインには細心の注意を払う必要がある。
どちらも不幸にならないために整理しておきたい。

- 前提
  - マネージャーとはなにか？マネージメントができている状態とは何か？
  - マネージメントも他技術職と同じで知識が必要
  - "面倒見がいいから"などは属性でしかなく、マネジメント適正の指標として盲信するのは危険
- 研修もないのに期待値だけ高い
  - 研修もなくいきなり業務から入ることになりがち
  - 期待値調整や、なぜ任命するのかを伝えるのはもちろん、部下たちにもお互いに歩み寄る姿勢が必須だというマインドは持ってもらう必要がある
- マネージャーにアサインする基準
  - プレイヤーとして優秀だったがマネージャーになると機能しない人もいる話
    - [ピーターの法則](https://ja.wikipedia.org/wiki/%E3%83%94%E3%83%BC%E3%82%BF%E3%83%BC%E3%81%AE%E6%B3%95%E5%89%87)
    - [専門家はマネジメントできない](https://scrapbox.io/nishio/専門家はマネジメントできない)
  - 組織的な課題解決にモチベーションが高い
  - ロバート・キーガンの成人発達理論で言うところの、少なくともレベル4以上が見込めないとリーダーシップは発揮しづらい
    - [組織も人も変わることができる! なぜ部下とうまくいかないのか 「自他変革」の発達心理学](https://www.amazon.co.jp/%E7%B5%84%E7%B9%94%E3%82%82%E4%BA%BA%E3%82%82%E5%A4%89%E3%82%8F%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B%EF%BC%81-%E3%81%AA%E3%81%9C%E9%83%A8%E4%B8%8B%E3%81%A8%E3%81%86%E3%81%BE%E3%81%8F%E3%81%84%E3%81%8B%E3%81%AA%E3%81%84%E3%81%AE%E3%81%8B-%E3%80%8C%E8%87%AA%E4%BB%96%E5%A4%89%E9%9D%A9%E3%80%8D%E3%81%AE%E7%99%BA%E9%81%94%E5%BF%83%E7%90%86%E5%AD%A6-%E5%8A%A0%E8%97%A4%E6%B4%8B%E5%B9%B3-ebook/dp/B01DW4YT6G/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=)
- 書籍は読もう
  - [THE TEAM](https://www.amazon.co.jp/TEAM-5%E3%81%A4%E3%81%AE%E6%B3%95%E5%89%87-NewsPicks-Book/dp/4344034546/ref=sr_1_1?adgrpid=52702658589&gclid=EAIaIQobChMI5sGK7b275AIVjGkqCh0GYwQTEAAYASAAEgKZ4_D_BwE&hvadid=338536179984&hvdev=c&hvlocphy=1028853&hvnetw=g&hvpos=1t1&hvqmt=e&hvrand=6031364742179649511&hvtargid=kwd-296648041150&hydadcr=2770_11133768&jp-ad-ap=0&keywords=the+team&qid=1567748387&s=gateway&sr=8-1)
  - [THE CULTURE CODE](https://www.amazon.co.jp/dp/B07L2HDSHH/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1)
  - [マネジメント](https://www.amazon.co.jp/%E3%83%9E%E3%83%8D%E3%82%B8%E3%83%A1%E3%83%B3%E3%83%88%EF%BC%BB%E3%82%A8%E3%83%83%E3%82%BB%E3%83%B3%E3%82%B7%E3%83%A3%E3%83%AB%E7%89%88%EF%BC%BD-%EF%BC%B0-%EF%BC%A6-%E3%83%89%E3%83%A9%E3%83%83%E3%82%AB%E3%83%BC-ebook/dp/B0083ZDWPE/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=)
  - [チームが機能するとはどういうことか](https://www.amazon.co.jp/%E3%83%81%E3%83%BC%E3%83%A0%E3%81%8C%E6%A9%9F%E8%83%BD%E3%81%99%E3%82%8B%E3%81%A8%E3%81%AF%E3%81%A9%E3%81%86%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%81%8B-%E2%80%95-%E3%80%8C%E5%AD%A6%E7%BF%92%E5%8A%9B%E3%80%8D%E3%81%A8%E3%80%8C%E5%AE%9F%E8%A1%8C%E5%8A%9B%E3%80%8D%E3%82%92%E9%AB%98%E3%82%81%E3%82%8B%E5%AE%9F%E8%B7%B5%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81-%E3%82%A8%E3%82%A4%E3%83%9F%E3%83%BC%E3%83%BB%EF%BC%A3%E3%83%BB%E3%82%A8%E3%83%89%E3%83%A2%E3%83%B3%E3%83%89%E3%82%BD%E3%83%B3-ebook/dp/B00N8J1NPQ/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1567748532&sr=8-1)
- etc

**Comment by yu-kgr** [comment]
マネジメントに対する課題は弊社でもとても感じている。
- 弊社はマネジメント研修を実施している。
- 次の段階として、リードできる技術者をとりにいっている

マネジメントは役割でしかない。
=> 役割でしかないので、必要とされる役割を達成する必要があるよね。
=> 役割を達成するために、必要なことをやるために必ずしも好かれる必要はない。
