### ISSUE TITLE
2019 Best OIMO

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#26]
2019年を振り返ったOIMO

1. 語ったトピックについて
2. 今年のやっていき具合はどうだったか
3. OIMOfmやってみた感想

**Comment by yu-kgr** [comment]
## 1

- 詐欺師症候群
- 自己肯定感が低い問題
- カンファレンス参加の所感
- コンフォートゾーンを超える挑戦
- 情熱プログラマーみたいな生き方
- 認知療法について

## 2

- フロントエンド歩み寄り学習
- スペシャリストの幸せな採用とは
- オンボーディングむつかしい

## 3

- 転職のタイミングってなんなんだろうね？
- リモートワークってどうですか？
- ゲーム最近やってます？

**Comment by yu-kgr** [comment]
- 詐欺師症候群
  - 以外と話題にあげられた
- 自己肯定感が低い問題
  - 自己肯定感上がりました？ 
  - 戦うべきは自分である！過去の自分と比べるとできる事が増えている感はある
- コンフォートゾーンを超える挑戦
  - 転籍 is 超える体験 / コミュニティ立ち上げ
- 認知療法について
  - 認知の歪みはどこにでもあるんだなぁ

**Comment by yu-kgr** [comment]
今年のやっていき具合はどうだったか
- アホみたいなBOT
- kanazawa.js

**Comment by yt-ymmt** [comment]
今年のやっていき

- EMやってます（死にそう
- 採用難しい （面接難しい
