### ISSUE TITLE
図式化する技術

### ISSUE THREAD

**Issue by yt-ymmt** [yu-kgr/oimo.fm#27]
- 会議などで話しながら議論内容を図にする能力が異常に高い人って一定数いる
- グラレコみたいなイラストレーション的なスキルではなく、議論や状況をマッピングする能力が高いことを指す
- この特殊能力ってどうやってゲットするのだろう...？
- 訓練方法とかってあるんだろうか

**Comment by yu-kgr** [comment]
田中ｶﾂﾉﾘｨ…

**Comment by yt-ymmt** [comment]
図解思考って言うみたいですね
本でも読んでみようかな
