### ISSUE TITLE
エンジニア -> マネージャー になったときの失敗あるある

### ISSUE THREAD

**Issue by yt-ymmt** [yu-kgr/oimo.fm#28]
### 仕組みとかプロセスで解消しがち
- 課題
  - プログラム脳になっているとツールや仕組みで解決しようとしがち
  - ツールで解決しようとすると水際対策にしかならず組織メンバーの成長につながらない
- どうするか？
  - 各個人の振る舞いを見直す必要がある
    - ペアプロ、モブプロなどエクストリームプログラミングを実践する etc
  - 知的な筋トレをチームとして実行する
  - 水際対策ももちろん必要

**Comment by yu-kgr** [comment]
`なっとき`
Typoォ！

**Comment by yt-ymmt** [comment]
memo)
この課題は [学習する組織](https://www.amazon.co.jp/dp/4862761011) という本を読んで整理できました。
https://www.slideshare.net/yukke0704/ss-10533844
