### ISSUE TITLE
Afterコロナな世界線、どう過ごしてますか？

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#32]
いまさらですが、コロナ前と後て生活スタイルが変化する人も多くなったかと思うのですが、
どのように変化したのかをざっくばらんに話したいです

自分としては、

- 仕事に関しては完全にフルリモート状態
- 色々な勉強会がオンラインで開催されてて嬉しい気持ち
- 家族と過ごせる時間が増えて嬉しい
- ただし、運動不足が課題

という感想。

**Comment by yu-kgr** [comment]
## 論点をどうするか

- 生活
  - 物流が滞ることによる購買行動の変化
  - オフライン => オンラインでの飲み会
- 仕事
  - オンライン上のコミュニケーション
- 世の中の空気

この先生きのこるには

**Comment by yt-ymmt** [comment]
### 1. 世の中
- 商品などが買い占められ必要としている人に必要なものが届かなくなっている
- 子育て世代が保育園の閉園と仕事の両立で消耗
- 自粛警察など含め全体的に余裕がない感じ、報道もそれを助長する内容
- 人の嫌なところがダイレクトに見えて辛い感じ

### 5.リモートワーク
- 楽になったところ、辛くなったところ
- 仕事とプライベートの境界線がなくなる
- 雑談や人の顔を見る機会が減り、孤独感が生まれる
- リモートワークにおけるマネジメント
  - ジョブ型（仕事に人をあてる）とメンバーシップ型（人に仕事をあてる）によってリモートワークが向いてる向いてないがありそう => 各々タイプごとのマネジメントとは・・・

### 6. 病んできたら
- 前提として持続可能性を一番にしましょう
- 普段と同じパフォーマンスは出せないと割り切りましょう
- 小さな達成感を積み重ねる
- 気分転換の手段を持ちましょう
- 人と比較するのをやめましょう
- 空気（Co2）大事 => Co2メーターめっちゃ高い

**Comment by yu-kgr** [comment]
### 2. ソーシャルディスタンス

- なんか小池さんの密です！っていうゲーム作られてたのを見た
  - Unityやらシューティングっぼいものやら
- 密集合防止のためのオンライン飲み会
  - いろんなサービスがある
  - みなさんどんな感じでやってます？
  - 人数増えると破綻する気がする
  - 組成されたばかりの状態でのオンライン飲み会の正解がわからない
- スーパーでは線をひいてあったり、レジにビニールで幕がはってあったり

### 3.転売屋について

- ゲーム機本体、粉もの、マスク、紙など

### 4.サービスについて

- オンラインでできることはオンラインになっていっている
- [自宅で入社手続き - SMART HR](https://smarthr.jp/lp/tele_02/)

**Comment by yt-ymmt** [comment]
### ビデオ会議
高画質化されたい
- [SIGMA fpをWEBカメラ化し、活用していくための留意点｜青木 優 | MATCHA Inc.｜note](https://note.com/aokiu/n/n3c2aeb4011b2)
- [【レビュー】一眼レフ、ミラーレスカメラがWEBカメラになる！キャプチャーボードの使い方 - スカイフィッシュのドローンブログ | カメラ・ガジェット・ドローンの撮影レビュー](https://www.droneskyfish.com/entry/webcam)

### slackのマナー
![image](https://user-images.githubusercontent.com/5885283/81562328-9d9c4900-93cf-11ea-9812-b87c543a83c8.png)
