### ISSUE TITLE
効率的な学習の話について

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#34]
最近どう学んでますか？

- 学び方のひとつとして、ペアプロ / モブプロとかあるよね。
  - でもこれ文化としてない場合、業務でどう取り入れていくの？
  - もしも業務で難しい場合、プライベートでできるもんなのかしら？

- 個人的にはUdemyがインプットするのが効率よさそう
- 読書 : 細かい所の意味が気になって、なかなか読み進まない && コード書きたくなって頭がどっか飛んでいく（技術書に限っては）

- いっそコード書いちゃう
  - くせえコードを排出してる感を感じる書けば書くほどリファクタリングが難しくなる空気がぷんぷんするぜー！的な

- ひとによってスムーズに学べる学習方法って異なったりすんのかしら？
  - 人に対するコミュニケーションにおいて、感覚タイプによってその人に対する説明や接し方を変えると伝わりやすいというものがあるが…（視覚型、聴覚型、触覚・運動型）
    - 視覚型は、図・イメージとして浮かぶものであればすぐ要点を掴むことがうまいが、説明・データ・イメージがわかないものは理解しづらい
    - 聴覚型は、理路整然としたデータ・数値・時間などを元に理解しやすいが、感覚的なものはわかりづらい。
    - 触覚・運動型の場合、五感を生かした表現が得意だが、理詰め・五感に来ないものはわかりづらい。
  - 自分は視覚型な気がする・・・。

**Comment by yt-ymmt** [comment]
![image](https://user-images.githubusercontent.com/5885283/93668108-7d8b3d80-fac5-11ea-98dc-435e5781fbf6.png)

- 人はラーニングゾーンにいることで成長が最大化される
- ラーニングゾーンは”適切な支援のもと達成可能な課題レベル”
- つまり１人で闇雲に学習するだけでは最適ではない
- 開発者とレビュアーの関係性は学習的観点から見ても有効

**Comment by yt-ymmt** [comment]
- ペアプロ / モブプロ
  - あえてペアプロなどの言葉を使わずにコード書いてみるからちょっと見ててもらえますか？などで良いかと思いました
- いっそコード書いちゃう
  - 構文などを理解するためになにか作るのは良いと思います
    - 作るものがないとモチベーションわかない人も多いはず
  - コードを書くことによって何を学習しようとしているかのイメージを持つことが大事ですね
    - 学習するときに何を習得しようとしているか意識していたほうが効率全然いい
