### ISSUE TITLE
OIMO.fm #0 / Discussion

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#4]
## 現在出てるトピック

- 転職を考える（た）とき
- 詐欺師症候群について
- 褒め言葉を深読みしすぎる問題
- コンフォートゾーンを超える挑戦について

**Comment by yt-ymmt** [comment]
- 1on1 流行ってるけどやってます？（頻度とか具体的にどうやってるか etc）
- スペシャリスト（技術が特化している人材）は業務委託などで技術顧問として入ってもらうほうが win-win なのではないか
- ラストスパート指向を見直そうとしている
- [情熱プログラマー](https://atuweb.net/201712_most-unskillfulness-in-a-team/)みたいな生き方どうなんじゃろ

**Comment by yu-kgr** [comment]
#0 案 -- 20minほど

---
* 自己紹介
* このpodcastについて
* 詐欺師症候群について
* 褒め言葉を深読みしすぎる問題
* コンフォートゾーンを超える挑戦について
* [情熱プログラマー](https://atuweb.net/201712_most-unskillfulness-in-a-team/)みたいな生き方どうなんじゃろ

**Comment by yt-ymmt** [comment]
山本といいます。
株式会社Kaizen Platform で フロントエンドエンジニア をやっています。
8月くらいに転職をして、最近はReactを使ったSPAを作っています。
前職でマネージメント経験があるのでチームビルドなどに興味があります。

**Comment by yu-kgr** [comment]
## このpodcastについて

石川県某所と東京を繋いで、とりあえずお互いが各々思っていることをアウトプットしつつ壁打ちするpodcastです。とりあえずやってみよう精神から始まりました。

OIMO.fmになっている理由としては、
Output In My Opinion の略で俺が思うに！ということをアウトプットしようぜ！
みたいな所を考えてます。

**Comment by yu-kgr** [comment]
どうもミナカワです。
金沢の某社で、いちディベロッパーをやっています。
ちょっと前まで、どちらかというとマネジメント寄りの業務を担当してたんですが、
今は、いちスクラムチームの開発者としてデザインからチームビルドからバックエンドまで、
いろいろやってるよくわからないおじさんです。
現場から離れすぎてエンジニア力が弱いので、そこらへんを向上させる事に必死になっています

**Comment by yu-kgr** [comment]
初回分をアップしました。
https://anchor.fm/oimofm/episodes/OIMO-fm-0-podcast-e3aj2k

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yu-kgr** [comment]
### 以下、#0のKPT

**Comment by yu-kgr** [comment]
まだWIPなので思いついたらEDITする

### KEEP

- 収録した音源をExportしてMacに送る事も可能だが、予想以上にanchorだけで完結するのが便利だった
- 声の大きさやしゃべる速度などは現状ままでもいけそうな感触

### PROBLEM

- 個人的な口癖「とりあえず / まぁ」が多すぎて笑った
- セクションごとに意識して何も言わない「間」を用意しないと編集が大変そう

### TRY
