### ISSUE TITLE
OIMO.fm #1 / Discussion

### ISSUE THREAD

**Issue by yu-kgr** [yu-kgr/oimo.fm#5]
1回目の内容について

**Comment by yu-kgr** [comment]
### 持ち越し話題

* 転職を考える（た）とき
* 1on1 流行ってるけどやってます？（頻度とか具体的にどうやってるか etc）
* スペシャリスト（技術が特化している人材）は業務委託などで技術顧問として入ってもらうほうが win-win なのではないか
* ラストスパート指向を見直そうとしている

**Comment by yt-ymmt** [comment]
- フリーライドする働き方の懸念

**Comment by yt-ymmt** [comment]
俺だけが頑張ってるという感情は危険
http://konifar-zatsu.hatenadiary.jp/entry/2017/09/25/153806

- こういうのに勝手にはまっていく人はいそう

**Comment by yt-ymmt** [comment]
45歳以上に対し、早期退職・希望退職者募集の嵐が吹き荒れているということ
https://www.orangeitems.com/entry/2019/03/24/000500

- わりと他人事ではない感じがする

**Comment by yt-ymmt** [comment]
オンボーディングのはじめかた
https://quipper.hatenablog.com/entry/2019/03/25/sre-onboarding

- 新人に疎外感を与えず、パフォーマンス発揮してもらうのってめっちゃむずくないですか

**Comment by yu-kgr** [comment]
継続化のためにやっている事などあれば聞きたい

- 公私共に、色々気になり継続が難しいマンなので。。

**Comment by yu-kgr** [comment]
フレックス / リモートワークという働き方ってどうですか

- これから少しずつ取り入れられていきそうですが、今の所まだ未体験なのでキニナル

**Comment by yu-kgr** [comment]
嫁との情報共有とかってどうしてます？

- プロジェクト名 : 家庭マネジメント

**Comment by yt-ymmt** [comment]
> 継続化のためにやっている事などあれば聞きたい
> 公私共に、色々気になり継続が難しいマンなので。。

[翻訳]あなたがプログラミングに向いていない10のサイン / 学習と理解に焦る
https://qiita.com/hareku/items/4bfc48e23e83e0d300f3#5--%E5%AD%A6%E7%BF%92%E3%81%A8%E7%90%86%E8%A7%A3%E3%81%AB%E7%84%A6%E3%82%8B

**Comment by yu-kgr** [comment]
フロントエンドの体系的な学習ってどうしました？

- サーバーサイドの学習は体系だったものがある気がするけど、フロントってそこらへん散らばってるものを拾い集める印象があるんですが、バイソンさんはどのように学習していったのか？という素朴な疑問

**Comment by yu-kgr** [comment]
人材の採用時に重視したいものとは

- カルチャーフィットやらスキルやらあると思うけど、どこを重視しますか？という話
- 個人的にはその方の人間性とカルチャーフィットがとても大事だと思っていて、ここをミスった場合のExitManagementは修羅みある

**Comment by yu-kgr** [comment]
>転職を考える（た）とき

これは2回目あたりにぶち込めそう

**Comment by yu-kgr** [comment]
>1on1 流行ってるけどやってます？（頻度とか具体的にどうやってるか etc）

弊社でもお上の声が出て、色々な所で行い始めた傾向があるが…

- 何を実現するためにやっていて、誰のためのものなのかがふわっとしてる感を感じた。
- まだまだとりあえずやっているという印象がある。
- 自分がやってたときは、行う目的を明確化、事前にアンケートを送信して、当日に答える内容を熟考してもらって話す。頻度は隔週に1回程度。我々が目指す目標に対して、個々でどういう課題があるのか？というものを軸とした話をしていた。

**Comment by yu-kgr** [comment]
>スペシャリスト（技術が特化している人材）は業務委託などで技術顧問として入ってもらうほうが win-win なのではないか

- 前述の採用時のカルチャーフィットだったりに関連するが、会社の動機理由が技術寄りなのか、会社のプロダクトに対してなのかによって左右されると思っている。
- 前者の場合は同意。後者の場合は会社のプロダクトをよくするために追い求めていった結果として、勝手にスペシャリスト化しちゃった系の人材になるのかなーと思ったり

**Comment by yt-ymmt** [comment]
### Topic
- 継続化のためにやっている事
    - Yamamoto
        - 新しい習慣を身につけるために必要とされるのは平均して66日間
        - エビングハウスの忘却曲線
            - https://ryugaku-kuchikomi.com/blog/ebbinghaus-the-forgetting-curve/
- 1on1やってる？
    - Minakawa
        - 弊社でもお上の声が出て、色々な所で行い始めた傾向があるが…
            - 何を実現するためにやっていて、誰のためのものなのかがふわっとしてる感を感じた。
            - まだまだとりあえずやっているという印象がある。
            - 自分がやってたときは、行う目的を明確化、事前にアンケートを送信して、当日に答える内容を熟考してもらって話す。頻度は隔週に1回程度。我々が目指す目標に対して、個々でどういう課題があるのか？というものを軸とした話をしていた。
    - Yamamoto
        - 開始直後はラポール形成を意識して雑談ベースから入るのもいいかも
        - 普段からコミュニケーションがそこそこ取れているのなら、形式張ってもわりとついてこれそう
        - 謙虚・敬意・信頼が必要
        - 課題を指摘したり、答えを教える存在ではなく、メンティが階段を上る手助けをするべき（ってエンジニアリング組織論への招待に書いてありました）
- 採用
    - 人材の採用時に重視したいもの
        - Minakawa
            - カルチャーフィットやらスキルやらあると思うけど、どこを重視しますか？という話
            - 個人的にはその方の人間性とカルチャーフィットがとても大事だと思っていて、ここをミスった場合の ExitManagement は修羅みある
        - Yamamoto
            - 人間性は前提として重要
            - JDとその期待値にマッチできるか
            - マネジメント力が高い組織ならある程度情報処理能力が低くなってもカバーできる。逆も然りなので今どれだけマネジメントできているのか把握する必要がある
            - 面接を異常な回数こなすと最初の挨拶時に合否判定出せるセブンセンシズに目覚めることができる模様 
    - スペシャリストは業務委託で入ってもらうほうがお互いwin-winなのでは？
        - Minakawa
            - 前述の採用時のカルチャーフィットだったりに関連するが、会社の動機理由が技術寄りなのか、会社のプロダクトに対してなのかによって左右されると思っている。
            - 前者の場合は同意。後者の場合は会社のプロダクトをよくするために追い求めていった結果として、勝手にスペシャリスト化しちゃった系の人材になるのかなーと思ったり
        - Yamamoto
            - スペシャリストがある意味満足できる業務を常に用意することが難しい
            - OSSの活動や複数の会社に対して技術顧問など行ってもらったほうがお互いに良いのではないか？
            - 相談役としてslackにはjoinしてもらっておくみたいな
- フロントエンドの体系的な学習（越境の仕方を含む）
    - Minakawa
        - サーバーサイドの学習は体系だったものがある気がするけど、フロントってそこらへん散らばってるものを拾い集める印象があるんですが、バイソンさんはどのように学習していったのか？という素朴な疑問
    - Yamamoto
        - 前提として自分はそんなに優秀じゃないですがという前置き
        - エンジニアとして Will / Can / Must を意識することは大切
        - SPAを作りたいとすると
            - SPAとはなにか？構成素子は？分解した最小単位は？その中でデファクトスタンダードなのはどれ？それがスタンダードなのはなぜ？
        - ある程度の必要知識をまとめたドキュメンテーション
        - 業務委託でスペシャリストにjoinしてもらう（相談役的な）
- フレックス / リモートワークという働き方
    - Yamamoto
        - リモートワークはただのツールという概念として捉えている
        - オフラインで一瞬で終わるコミュニケーションも存在するため、ただ楽になるだけではない
        - 情報の非対称性をできるだけ作らないように `ジョハリの窓` を意識し続けることが必要
            - https://potect-a.com/wp-content/uploads/2018/10/johari-no-mado5.jpg
- 嫁との情報共有
    - Yamamoto
        - trello を導入したけれどリテラシーの差が発生し、冷蔵庫に貼ったホワイトボードに書くというアナログなソリューションに落ち着いた...
        - 旅行などの計画は notion で自分が作成して共有している

### Other
- 転職を考える（た）とき
- フリーライドする働き方の懸念
- 俺だけが頑張ってるという感情は危険
    - http://konifar-zatsu.hatenadiary.jp/entry/2017/09/25/153806
- 45歳以上に対し、早期退職・希望退職者募集の嵐が吹き荒れているということ
    - https://www.orangeitems.com/entry/2019/03/24/000500
- オンボーディング
    - https://quipper.hatenablog.com/entry/2019/03/25/sre-onboarding
- マネージメントとは
    - ハイアウトプットマネージメント

**Comment by yu-kgr** [comment]
なんかものすごいまとめられている！

**Comment by yt-ymmt** [comment]
### 企画案
「なんか」とか口癖などをした分だけ募金する

**Comment by yu-kgr** [comment]
話してみる内容

1. フロントエンドの体系的な学習（越境の仕方を含む）
  a. デザイナー出身とサーバーサイドエンジニア出身の方がいるけどどっちからもフロントに進む人いるけど、どう越境すると学びやすいんだろうねという感じ。
  b.  業務の場合は、技術コンサルというかスペシャリストにJOINしてもらうとか → 採用の話しに
2. 採用
 a. 人材の採用時に重視したいもの
 b. スペシャリストは業務委託で入ってもらうほうがお互いwin-winなのでは？
 c. オンボーディングってどうしてます？
   1. 弊社だと最近新卒教育がめっちゃフロントからバックエンドまで盛り盛りの構成になってて技術的なサポートはすごい。ただし事業配属になった後のオンボーディングでいうとどうだろうかという課題はまだあるような気がする

**Comment by yt-ymmt** [comment]
### Anchor 安定しない問題
- PCで録音するものありなのかしら
- [yatteiki.fm Podcast 環境 2017 – r7kamura – Medium](https://medium.com/@r7kamura/yatteiki-fm-podcast-%E7%92%B0%E5%A2%83-2017-c3dbaaeea7d3)

**Comment by yu-kgr** [comment]
padcastのアジェンダを
`1. 2. 3. 4. みたいな感じでテンプレ用意する`

**Comment by yu-kgr** [comment]
### 骨格
1. podcastについて
2. 自己紹介
3. なんか適当な話し
4. 本題
5. 本題
6. エンディング

**Comment by yu-kgr** [comment]
話した内容

1. 採用
2. 学習
3. オンボーディング

からの、

`親族のおもてなしでGWの半分以上が溶けてしまったミナカワ`

**Comment by yu-kgr** [comment]
辛いことがあった場合のマインドコントロール術

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
